### ISSUE TITLE
Deprecation warning on startup: "Passing command to redis as is"

### ISSUE THREAD

**Issue by jaredbeck** [resque/resque-scheduler#600]
Deprecation warnings on startup:

```
13:07:00 scheduler.1 | Passing 'info' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /Users/jared/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/resque-1.27.2/lib/resque/data_store.rb:60:in `method_missing')
13:07:00 scheduler.1 | Passing 'script' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /Users/jared/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/resque-1.27.2/lib/resque/data_store.rb:60:in `method_missing')
13:07:00 scheduler.1 | Passing 'script' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /Users/jared/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/resque-1.27.2/lib/resque/data_store.rb:60:in `method_missing')
```

The timestamp and process identifier (`scheduler.1`) come from foreman.

Then, on shutdown,

```
13:09:40 scheduler.1 | resque-scheduler: [INFO] 2017-02-21T13:09:40-05:00: Got INT signal
13:09:40 scheduler.1 | resque-scheduler: [INFO] 2017-02-21T13:09:40-05:00: Shutting down
13:09:40 scheduler.1 | rake aborted!
13:09:40 scheduler.1 | Redis::CommandError: NOSCRIPT No matching script. Please use EVAL.
13:09:40 scheduler.1 | /Users/jared/.rbenv/versions/2.2.5/bin/bundle:23:in `load'
13:09:40 scheduler.1 | /Users/jared/.rbenv/versions/2.2.5/bin/bundle:23:in `<main>'
13:09:40 scheduler.1 | Interrupt: Interrupt
13:09:40 scheduler.1 | /Users/jared/.rbenv/versions/2.2.5/bin/bundle:23:in `load'
13:09:40 scheduler.1 | /Users/jared/.rbenv/versions/2.2.5/bin/bundle:23:in `<main>'
13:09:40 scheduler.1 | Tasks: TOP => resque:scheduler
13:09:40 scheduler.1 | (See full trace by running task with --trace)
13:09:40 scheduler.1 | exited with code 1
```

Maybe they are related, because one says "Passing 'script' command" and the other says "No matching script"? I don't know what redis scripts are, though.

Versions:

```
bundle | ggrep -i resque
Using resque 1.27.2
Using resque-scheduler 4.3.0
Using resque-retry 1.5.0
Using capistrano-resque 0.2.3
ruby -v
ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-darwin15]
```

**Comment by jaredbeck** [comment]
A similar deprecation warning was recently fixed in resque (https://github.com/resque/resque/issues/1539)

**Comment by carsonreinke** [comment]
I think one is just a deprecation warning, unless that is warning that actually will not pass through.  The other is Redis complaining that the Lua script has not been loaded, which probably should not be happening.

What version of redis-namespace are you using?

**Comment by jaredbeck** [comment]
> What version of redis-namespace are you using?

```
bundle | ggrep -i redis
Using redis 3.3.3
Using redis-namespace 1.5.3
Using redis-store 1.2.0
Using redis-rack 2.0.0
Using redis-activesupport 5.0.1
Using redis-actionpack 5.0.1
Using redis-rails 5.0.1
```

**Comment by carsonreinke** [comment]
Looks like master has better handling of the Redis script.  Any chance you had Redis restart without restarting the resque-scheduler task?  I really don't think Redis replicates the script cache.

**Comment by jaredbeck** [comment]
> Looks like master has better handling of the Redis script.

Cool! So these deprecation warnings will go away with the next release of resque-scheduler?

> Any chance you had Redis restart without restarting the resque-scheduler task?

I'm not sure. We use foreman to start Redis and resque-scheduler in parallel. The Procfile looks like this:

```
rails: passenger start --port $PORT
redis: redis-server
scheduler: bundle exec rake environment resque:scheduler
worker: VERBOSE=1 bundle exec rake environment resque:work QUEUE=*
gulp: gulp watch
```

**Comment by carsonreinke** [comment]
> Cool! So these deprecation warnings will go away with the next release of resque-scheduler?

No, this probably needs to be changed either in resque so it delegates to the right object or resque-scheduler to not use `Resque.redis`.  You can ignore for now, redis-namespace is doing what it is suppose to do.

Do you receive the shutdown error consistently?

**Comment by jaredbeck** [comment]
>> Cool! So these deprecation warnings will go away with the next release of resque-scheduler?

> No, this probably needs to be changed either in resque so it delegates to the right object or resque-scheduler to not use Resque.redis. You can ignore for now, redis-namespace is doing what it is suppose to do.

Sorry Carson, I don't understand. How can I make these deprecation warnings go away? The resque people [told me][1] to open an issue here.

> Do you receive the shutdown error consistently?

Yeah, seems to be 100% of the time.

[1]: https://github.com/resque/resque/issues/1539

**Comment by carsonreinke** [comment]
@jaredbeck let me look into this, I think resque is expecting something different now.

**Comment by carsonreinke** [comment]
@jaredbeck I put in a PR for the first part, but the second part is quite mysterious.  Any idea what version of Redis you are running?

**Comment by jaredbeck** [comment]
> I put in a PR for the first part ..

Thanks!

> .. the second part is quite mysterious. Any idea what version of Redis you are running?

```
redis-cli --version
redis-cli 3.2.8
```

**Comment by carsonreinke** [comment]
@jaredbeck The only way I was able to reproduce the issue was by actually restarting redis-server.  However, instead of using v4.3.0 and I try with master, it does not cause that issue, as it actually checks to see if Redis has that script in its cache.

I'd like to consider this resolved now, let me know if you disagree.

**Comment by jaredbeck** [comment]
Sounds good to me. Thanks Carson.

**Comment by jaredbeck** [comment]
Hi Carson. I'm coming back to this issue after a few months, and still seeing these deprecation warnings when I start up resque-scheduler.

```
11:24:52 scheduler.1 | resque-scheduler: [INFO] 2017-05-10T11:24:52-04:00: Starting
...
11:24:52 scheduler.1 | resque-scheduler: [INFO] 2017-05-10T11:24:52-04:00: Schedules Loaded
11:24:52 scheduler.1 | Passing 'info' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /Users/jared/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/resque-1.27.4/lib/resque/data_store.rb:59:in `method_missing')
11:24:52 scheduler.1 | Passing 'script' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /Users/jared/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/resque-1.27.4/lib/resque/data_store.rb:59:in `method_missing')
```

> However, instead of using v4.3.0 and I try with master, it does not cause that issue ..

It sounds like the next released version of resque-scheduler will no longer print these deprecations warnings? If so, is there an ETA on the next release? Thanks.

**Comment by carsonreinke** [comment]
PR is ready and waiting https://github.com/resque/resque-scheduler/pull/602

Really v4.3.1 should be released with that.

**Comment by zedtux** [comment]
@jaredbeck and @carsonreinke any progress on this?

**Comment by carsonreinke** [comment]
@zedtux Really need someone to double check this PR.  I could probably accept it myself, but unsure why damage I could cause :fire:

**Comment by Brotakuu** [comment]
Coming up with this error as well. Hope to see the PR merged @zedtux @carsonreinke .

**Comment by kristophM** [comment]
Hi @carsonreinke did this get resolved? I'm having these exact same issues and haven't been able to resolve.

**Comment by virgoproz** [comment]
Waiting for a resolution here as well. Let me know if I can help

**Comment by carsonreinke** [comment]
Fixed in #602

**Comment by jeremywadsack** [comment]
This appears to have been merged to master on 2018-01-28, but no release has been pushed since then. The latest release, v4.3.1, does _not_ include this change. Any chance of getting a new release out to fix these warnings?

**Comment by mmatviyiv** [comment]
any progress on that?

**Comment by tmedford** [comment]
Please can we get this.

**Comment by wandenberg** [comment]
Any updates on this? Can someone release at least a 4.3.2 version with this fix?
